languageCode = "en-us"
title = "Streaming Analytics Proofshop"
theme = "hugo-material-docs"
metadataformat = "yaml"
canonifyurls = true
baseUrl = "/"

disableKinds = ["taxonomy","taxonomyTerm"]

[params]
	description = "Streaming Analytics Proofshop"

	logo = "images/asset-hub.svg"
	favicon = "/images/asset-hub.png"

[params.palette]
    primary = "grey"
    accent  = "teal"

[params.font]
    text = "Roboto"
    code = "Roboto Mono"

[blackfriday]
	smartypants	= true
	fractions = true
	smartDashes = true
	plainIDAnchors = true


[[menu.main]]
	name   = "Streaming Analytics Proofshop"
	url    = "/"
	weight = 10
[[menu.main]]
    name   = "Cumulative Streaming Calculations"
    url    = "cumcalc/"
    weight = 20
[[menu.main]]
    name   = "Streaming Monitoring and Performance Tuning"
    url    = "perf/"
    weight = 30
[[menu.main]]
    name   = "Build and Run"
    url    = "buildandrun/"
    weight = 90
